export const iconTexts = {
    "information": {
      "0": {
        "1": "User Motivations \n\n 📌 Finding from the Study: \n Users prioritize cost savings and convenience over ethical considerations, making unauthorized APKs an attractive option. \n\n 🔹 Abhijithoyur (2023) found that cost savings are the primary motivation for engaging in digital piracy. \n\n 📌 What This Means:\n✔ Users prioritize free access over ethics, often rationalizing piracy.\n✔ Many believe piracy doesn't harm developers or businesses.\n✔ Some feel justified in downloading pirated APKs when apps are region-locked or unavailable.\n\n🚨 The Reality:\n🔸 Unauthorized APK downloads expose users to malware, security risks, and legal consequences.\n🔸 Developers lose revenue, affecting their ability to create and update apps.\n\n✅ Solution:\nDevelopers should offer affordable pricing models, free trials, and student discounts to provide legal alternatives.",
        "2": "Cost-Saving as the Main Reason \n\n📌 Finding from the Study:\nThe financial barrier to purchasing apps is the most common reason for APK piracy.\n\n🔹 Maria & Maria (2024) found that users prioritize financial savings over premium features, especially when free apps offer similar functionality\n\n📌 What This Means:\n✔ Many users perceive paid apps as non-essential.\n✔ If a free alternative exists, users see no reason to pay.\n✔ Piracy becomes a habit, reinforcing free access expectations.\n\n🚨 The Reality:\n🔸 Paid apps struggle to compete with \"free\" pirated versions, even when they provide better security and support.\n🔸 Developers may increase app prices due to revenue losses, making piracy even more tempting\n\n✅ Solution:\nImplementing tiered pricing models and regional discounts can encourage users to choose legal options.",
        "3": "Ethics vs. Convenience\n\n📌 Finding from the Study:\nMany users acknowledge that piracy is unethical but still justify it based on convenience.\n\n🔹 Chin et al. (2021) found that users often ignore ethical concerns when piracy is the easiest option.\n\n📌 What This Means:\n✔ Users don’t see piracy as \"stealing,\" especially when it’s easy and anonymous.\n✔ Ethical concerns are often secondary to immediate benefits.\n\n🚨 The Reality:\n🔸 Ethical awareness alone doesn’t stop piracy—users need incentives to change behavior.\n🔸 The longer users engage in piracy, the harder it is for them to transition to legal alternatives.\n\n✅ Solution:\nPromoting legal, convenient alternatives with free trials and flexible payment plans can reduce piracy.",
        "4": "Lack of Awareness of Legal Risks \n\n📌 Finding from the Study:\nMany users do not fully understand the legal consequences of piracy.\n\n🔹 Tomczyk & Fedeli (2021) found that piracy remains widespread despite anti-piracy laws, as many users believe they won’t be caught.\n\n📌 What This Means:\n✔ Users assume piracy is a low-risk activity.\n✔ Laws against piracy are not well-communicated.\n\n🚨 The Reality:\n🔸 Many unauthorized APKs contain malware, leading to data breaches and identity theft.\n🔸 Legal action is increasing, making piracy riskier than before.\n\n✅ Solution:\nDigital literacy campaigns should inform users about piracy risks and legal consequences.",
        "5": "Role of Technology in Piracy\n\n📌 Finding from the Study:\Technology has made piracy easier but also increased cybersecurity threats.\n\n🔹 Li, Liao, & Xie (2021) found that piracy negatively impacts creative productivity and customer support in software industries.\n\n📌 What This Means:\n✔ Faster downloads and file-sharing platforms have fueled piracy growth.\n✔ Users often assume technological workarounds (VPNs, modded apps) will protect them.\n\n🚨 The Reality:\n🔸 Piracy continues to evolve, making enforcement difficult.\n🔸 More advanced malware attacks now specifically target APK piracy users.\n\n✅ Solution:\nEducating users on the risks of piracy-driven malware can encourage safer digital choices.",
        "6": "Faster Internet’s Impact on Piracy\n\n📌 Finding from the Study:\nFaster internet speeds increase unauthorized APK downloads by removing accessibility barriers.\n\n🔹 Citak (2023) found that high-speed internet allows illegal websites to distribute pirated content quickly and anonymously.\n\n📌 What This Means:\n✔ High-speed access removes deterrents, making piracy effortless.\n✔ Users become more dependent on piracy when downloads are instant.\n\n🚨 The Reality:\n🔸 Faster internet enables widespread malware infections through pirated content.\n🔸 Legitimate platforms struggle to compete with the convenience of illegal downloads.\n\n✅ Solution:\nLegal streaming and app platforms must offer affordable, high-quality services to discourage piracy."
      },
      "1": {
        "1": "Qualitative Findings: User Psychology & Perceptions\n\nJustification & Rationalization of Piracy\n\n📌 Finding from the Study:\nUsers don’t always see piracy as wrong, especially when apps are expensive or unavailable in their region.\n\n🔹 Chin et al. (2021) found that users justify piracy as a necessary alternative when official versions are inaccessible.\n\n📌 What This Means:\n✔ Users believe piracy is a workaround for unfair restrictions.\n✔ Some rationalize it by claiming companies already make enough money.\n\n🚨 The Reality:\n🔸 Piracy undermines the business models of developers, forcing them to adopt more restrictive monetization practices.\n\n✅ Solution:\nDevelopers should provide affordable, accessible alternatives such as regional pricing and freemium models.",
        "2": "Qualitative Findings: User Psychology & Perceptions\n\nPerceived Security of Unauthorized Apps\n\n📌 Finding from the Study:\nUsers assume some piracy sources are safe because they have not experienced security issues.\n\n🔹 De Leon et al. (2021) found that many MOD APKs contain hidden malware, exposing users to serious risks.\n\n📌 What This Means:\n✔ Users feel a false sense of security when using \"trusted\" piracy sources.\n\n🚨 The Reality:\n🔸 Even \"safe\" sources can embed spyware that activates later.\n🔸 Users unknowingly compromise personal data and financial accounts\n\n✅ Solution:\nRaising cybersecurity awareness about how hackers exploit APK piracy can help users avoid unsafe downloads.",
        "3": "Qualitative Findings: User Psychology & Perceptions\n\nAnti-Piracy Efforts vs. Workarounds\n\n📌 Finding from the Study:\nDespite anti-piracy laws and security measures, users find workarounds to continue piracy.\n\n🔹 Li, Liao, & Xie (2021) found that piracy constantly evolves alongside security measures.\n\n📌 What This Means:\n✔ Anti-piracy measures are often temporary solutions, as users find ways to bypass them.\n\n🚨 The Reality:\n🔸 Digital piracy is an ever-evolving problem requiring continuous monitoring and stricter enforcement.\n\n✅ Solution:\nStrengthening app security and piracy detection systems can help prevent APK modifications.",
        "4": "Qualitative Findings: User Psychology & Perceptions\n\nRisk Awareness vs. Convenience\n\n📌 Finding from the Study:\nMany users know the risks of piracy but still prioritize convenience.\n\n🔹 Chin et al. (2021) observed that users disregard security warnings when pirated apps offer immediate benefits.\n\n📌 What This Means:\n✔ Users believe short-term benefits outweigh risks.\n✔ Many assume security risks are exaggerated.\n\n🚨 The Reality:\n🔸 Pirated APKs often come with long-term security threats, including identity theft and financial fraud.\n\n✅ Solution:\nEducating users on the hidden dangers of piracy can shift perceptions.",
        "5": "Qualitative Findings: User Psychology & Perceptions\n\nDigital Literacy & Awareness\n\n📌 Finding from the Study:\nMany users lack proper education on piracy risks, leading to unsafe downloading habits.\n\n🔹 Tomczyk & Fedeli (2021) found that digital literacy campaigns significantly reduce piracy rates by informing users of security risks.\n\n📌 What This Means:\n✔ Users are not fully aware of the dangers associated with piracy.\n\n🚨 The Reality:\n🔸 Without proper awareness, users are more vulnerable to cyberattacks.\n\n✅ Solution:\nGovernments and organizations should support educational initiatives that teach users about safe digital practices and legal alternatives.",
        "6": "Quantitative Findings: Behavioral & Economic Impact\n\nFrequent Downloaders vs. Paid App Users\n\n📌 Finding from the Study:\nFrequent APK downloaders continue pirating apps out of habit, even when they can afford legal versions.\n\n🔹 Tomczyk (2021) found that habitual users disregard cost considerations when choosing between free and paid apps.\n\n📌 What This Means:\n✔ Even when apps are affordable, users stick to piracy due to familiarity.\n\n🚨 The Reality:\n🔸 Developers lose revenue, reducing investment in new features and security.\n\n✅ Solution:\nEducating users on the benefits of legal apps (security, reliability, and better user experience) can encourage them to transition away from piracy.",
        "7": "Quantitative Findings: Behavioral & Economic Impact\n\nImpact of Pricing & Accessibility\n\n📌 Finding from the Study:\nHigh app costs push users toward piracy, reinforcing the affordability-piracy link.\n\n🔹 Suarez et al. (2023) found that users perceive expensive apps as non-essential, leading them to seek free alternatives.\n\n📌 What This Means:\n✔ Many users cannot justify paying high prices for an app they use casually.\n\n🚨 The Reality:\n🔸 Overpriced apps lead to more piracy, rather than increased legitimate purchases.\n\n✅ Solution:\nImplementing flexible pricing models (freemium plans, student discounts, or regional pricing) can make legal purchases more accessible.",
        "8": "Quantitative Findings: Behavioral & Economic Impact\n\nCorrelation Between Technology & APK Downloads\n\n📌 Finding from the Study:\nTechnological advancements increase APK piracy rates by making piracy faster and more accessible.\n\n🔹 Li, Liao, & Xie (2021) found that digital piracy evolves alongside security measures, making enforcement difficult.\n\n📌 What This Means:\n✔ As new tools make piracy easier, illegal downloads increase.\n\n🚨 The Reality:\n🔸 Traditional anti-piracy measures become outdated fast, requiring constant adaptation.\n\n✅ Solution:\nStronger AI-driven piracy detection systems and collaborations between developers and cybersecurity firms can help reduce piracy.",
        "9": "Quantitative Findings: Behavioral & Economic Impact\n\nFree Alternatives & Piracy Behavior\n\n📌 Finding from the Study:\nThe availability of free alternatives increases piracy rates.\n\n🔹 Tian et al. (2021) found that users prefer free apps over paid ones, even if the experience is lower quality.\n\n📌 What This Means:\n✔ Free versions encourage habitual piracy, as users always choose the cheaper option.\n\n🚨 The Reality:\n🔸 The more free apps exist, the more piracy is normalized.\n\n✅ Solution:\nOffering better incentives for legal purchases (exclusive features, bonuses, or cross-app benefits) can encourage users to buy official apps."
      },
      "3": {
        "1": "Malware & Security Threats\n\n📌 Finding from the Study:\nMany pirated APKs contain hidden malware that can steal personal data, track activity, or compromise devices.\n\n🔹 De Leon et al. (2021) found that MOD APKs frequently contain embedded tracking scripts that monitor user activity.\n\n🚨 The Reality:\n🔸 Hackers embed spyware and keyloggers into unauthorized apps, leading to identity theft and financial fraud.\n\n✅ Solution:\nRaising cybersecurity awareness can help users avoid unsafe downloads.",
        "2": "Legal Consequences of Piracy\n\n📌 Finding from the Study:\nDownloading or distributing unauthorized APKs violates copyright laws, leading to fines or even jail time in some countries.\n\n🔹 Tomczyk & Fedeli (2021) found that anti-piracy enforcement is increasing, with governments shutting down illegal APK distribution sites and tracking IP addresses of users.\n\n🚨 The Reality:\n🔸 Some companies actively sue individuals for piracy, especially those who distribute or modify APKs.\n\n✅ Solution:\nChoosing legal alternatives ensures safety, app quality, and compliance with the law.",
        "3": "Impact on Developers & App Quality\n\n📌 Finding from the Study:\nLoss of revenue from piracy reduces funding for security updates, new features, and app improvements.\n\n🔹 Suarez et al. (2023) found that developers often discontinue apps or switch to ad-heavy, intrusive monetization models due to piracy losses.\n\n🚨 The Reality:\n🔸 If piracy continues, fewer high-quality apps will be developed, and existing ones will have weaker security, more ads, and fewer updates.\n\n✅ Solution:\nSupporting legal downloads and fair pricing models ensures a thriving digital ecosystem.",
        "4": "Copyright Infringement Penalties\n\n📌 Finding from the Study:\nIn many countries, piracy is a criminal offense, with penalties ranging from hefty fines to imprisonment.\n\n🔹 Citak (2023) found that governments have taken major actions against APK piracy, such as mass shutdowns of piracy websites and lawsuits against their owners.\n\n🚨 The Reality:\n🔸 Even if you’re an “individual downloader,” you can still be tracked and fined for piracy\n\n✅ Solution:\nLegal awareness campaigns can help educate users on the risks.",
        "5": "How Piracy Hurts Innovation\n\n📌 Finding from the Study:\nPiracy reduces app revenue, leading to budget cuts in development, security, and customer support.\n\n🔹 Maria & Maria (2024) found that startups and indie developers suffer the most, as they rely on app purchases to sustain business growth.\n\n🚨 The Reality:\n🔸 Instead of funding new innovations, resources are wasted on piracy protection measures rather than improving apps.\n\n✅ Solution:\nSupporting ethical digital choices encourages better app development.",
        "6": "Cybersecurity Risks from APKs\n\n📌 Finding from the Study:\nMOD APKs often contain spyware and malware that remain hidden until activated.\n\n🔹 Raj (2023): \"Even trusted piracy sources can distribute trojanized apps that steal passwords, banking data, and personal files.\"\n\n🚨 The Reality:\n🔸 Users who download pirated apps regularly are at higher risk of being targeted by hackers.\n\n✅ Solution:\nPublic awareness about real piracy-related cybersecurity breaches can help shift user behavior.",
        "7": "Personal Data & Identity Theft Risks\n\n📌 Finding from the Study:\nPirated apps often request excessive permissions, leading to unauthorized data collection.\n\n🔹 De Leon et al. (2021) found that users rarely check permissions before installing pirated APKs.\n\n🚨 The Reality:\n🔸 Hackers use APK piracy to steal passwords, contacts, and financial data.\n\n✅ Solution:\nEducating users about safe app permissions can reduce data theft incidents.",
        "8": "Fake & Unstable App Versions\n\n📌 Finding from the Study:\nMany pirated APKs are altered versions that lack security updates and new features.\n\n🔹 Tian et al. (2021) found that pirated apps frequently break after official updates.\n\n🚨 The Reality:\n🔸 Users often experience crashes, lost data, and unsupported features with pirated APKs.\n\n✅ Solution:\nPromoting the benefits of official app updates can encourage legal downloads.",
        "9": "Increased Ads & Microtransactions Due to Piracy\n\n📌 Finding from the Study:\nAs piracy increases, developers rely more on in-app ads and microtransactions to make up for lost revenue.\n\🔹 Maria & Maria (2024): \"When piracy rates go up, developers have no choice but to add more ads, paywalls, and microtransactions, making even legal apps frustrating to use.\"\n\n🚨 The Reality:\n🔸 Piracy forces developers to add aggressive ads and restrict content behind paywalls.\n\n✅ Solution:\nIf users support developers, they’ll receive better apps with fewer ads and improved security.",
        "10": "Expert Opinions on APK Piracy\n\n📌 Cybersecurity Specialists on APK Safety\n🔹 Raj (2023): \“Pirated APKs remain a major cyber risk. Even trusted piracy sources can distribute trojanized apps that steal passwords, banking data, and personal files.\”\n🔹 De Leon et al. (2021): \“MOD APKs frequently contain embedded tracking scripts that can monitor user activity—even when the app isn’t in use.\”\n\n📌 Developers on Piracy’s Effects\n🔹 Tian et al. (2021): \“Users think piracy only affects corporations, but the reality is, independent developers are the biggest victims—many shut down due to revenue losses.\"\n\n🚨 The Reality:\n🔸 Piracy doesn’t just affect companies—it lowers app quality for everyone.\n\n✅ Solution:\nMore public awareness and policy changes can help curb piracy's negative effects."
      }
    },
    "guide": {
      "0": {
        "1": "Finding Safe & Legal DownloadsFinding Safe & Legal Downloads\n\n✔ Always download apps from official stores (Google Play, Apple App Store).\n✔ Use trusted third-party stores (e.g., Amazon Appstore) for alternatives.\n✔ Avoid websites that offer \"modded\" or \"premium unlocked\" APKs—these are high-risk for malware.\n\n🚨 The Reality:\n🔸 Many piracy users don’t realize how many legal and affordable options exist.\n\n✅ Solution:\nPromoting alternative pricing models and raising awareness can reduce piracy rates.",
        "2": "Affordable, Legal App Alternatives\n\n✔ Freemium Apps – Many apps offer free versions with optional upgrades.\n✔ Student & Regional Discounts – Some apps adjust pricing based on location or student status.\n✔ Ad-Supported Models – Some free apps use ads instead of paywalls—a legal alternative to piracy.\n\n🚨 The Reality:\n🔸 Legal alternatives exist, but many users remain unaware of them.\n\n✅ Solution:\nMore visibility and awareness of these options can reduce piracy.",
        "3": "Boosting Digital Awareness\n\n📌 Steps to Protect Your Device from Malicious APKs\n✔ Enable Google Play Protect to block untrusted apps.\n✔ Use antivirus software to detect harmful downloads.\n✔ Check app permissions—if an APK asks for unnecessary access, it’s a red flag.\n\n📌 Checklist: Signs of a Risky App\n✔ The app asks for unusual permissions (e.g., a flashlight app asking for microphone access).\n✔ You can’t find it on official stores, or it has fake reviews.\n✔ It promises \“premium unlocked\” features for free—often a sign of a trojanized app.\n\n✅ Solution:\nPromoting device security awareness can prevent users from falling victim to cyber threats.",
        "4": "Strengthening Anti-Piracy Efforts\n\n✔ Digital Rights Advocacy – Raising awareness about how piracy affects app development.\n✔ Better Awareness Campaigns – Governments and tech companies should educate users on:\n\t• The dangers of unauthorized APKs\n\t• The benefits of supporting legal apps\n\t• How piracy harms the industry and users alike\n\n🚨 The Reality:\n🔸 Many developers haven’t adapted their pricing models, pushing users toward piracy.\n\n✅ Solution:\nEncouraging flexible app pricing and strong anti-piracy advocacy can reduce piracy.",
        "5": "Improving App Accessibility\n\n✔ Alternative Pricing Models – Developers should offer:\n\t• Freemium options – Free-to-use apps with optional upgrades.\n\t• Student & low-income discounts – Making legal downloads accessible for more users\n\t• Ad-supported models – Providing a free option without forcing piracy.\n\n🚨 The Reality:\n🔸 Many users engage in piracy because they cannot afford expensive apps.\n\n✅ Solution:\nMore affordable legal options can help reduce APK piracy."
      },
      "1": {
        "1": "Ethical Digital Policies Support\n\n📌 Why It Matters:\n✔ Fair pricing models can make legal apps more accessible.\n✔ Strengthening digital piracy laws protects developers.\n✔ Public awareness campaigns can educate users on the risks of APK piracy.\n\n🚨 The Reality:\n🔸 Many governments lack strong digital piracy laws or fail to enforce them properly.\n\n✅ Solution:\nEncouraging stronger policies ensures a safer digital environment.",
        "2": "Fair Pricing Advocacy\n\n📌 Why It Matters:\n✔ Many developers fail to offer affordable plans, pushing users toward piracy.\n✔ Fair regional pricing can help users in different economies access apps legally.\n\n🚨 The Reality:\n🔸 Overpriced apps push users toward piracy instead of legitimate purchases.\n\n✅ Solution:\nDevelopers should adapt pricing models to encourage legal purchases.",
        "3": "Stronger Digital Piracy Laws\n\n📌 Why It Matters:\n✔ Current anti-piracy laws are often outdated or ineffective.\n✔ Stronger enforcement can help reduce piracy rates.\n\n🚨 The Reality:\n🔸 Many governments fail to actively enforce anti-piracy laws, making piracy low-risk for users.\n\n✅ Solution:\nStronger international cooperation can improve digital piracy prevention.",
        "4": "Public Awareness Campaigns\n\n📌 Why It Matters:\n✔ Many users don’t realize how piracy affects app development.\n✔ Raising awareness about security risks can change behavior.\n\n🚨 The Reality:\n🔸 Many users believe piracy is harmless, not realizing its broader impact.\n\n✅ Solution:\nEducational campaigns can help shift public perception about piracy risks."
      },
      "3": {
        "1": "Users Who Switched from Piracy\n\n📌 What They Say:\n✔ Many users regret engaging in piracy after facing malware or legal warnings.\n✔ Some switched after realizing piracy hurts developers and leads to low-quality apps.\n\n🚨 The Reality:\n🔸 Users who switched now enjoy a safer, ad-free, and updated app experience.\n\n✅ Solution:\nPromoting these real stories can help convince more people to switch to legal downloads.",
        "2": "Developers Affected by APK Piracy\n\n📌 What They Say:\n✔ Independent developers struggle to survive due to piracy-related revenue loss.\n✔ Many developers discontinue apps because they cannot afford to maintain them.\n\n🚨 The Reality:\n🔸 The more users engage in piracy, the fewer quality apps are developed.\n\n✅ Solution:\nRaising awareness about the impact of piracy on developers can discourage illegal downloads."
      },
      "4": {
        "1": " Guide to Recognizing Unsafe APKs\n\n📌 Key Indicators of Pirated APKs:\n✔ APKs from unverified sources often contain malware.\n✔ Apps that request unnecessary permissions may be dangerous.\n\n🚨 The Reality:\n🔸 Many users download malware-infected apps without realizing the risks.\n\n✅ Solution:\nEducating users on how to verify safe apps can reduce cyber threats.",
        "2": "Checklist for Safe App Downloads\n\n📌 Before Downloading an App, Ask Yourself:\n✔ Is it from an official store?\n✔ Does it have authentic user reviews?\n✔ Does it request reasonable permissions?\n\n🚨 The Reality:\n🔸 Many users skip basic security checks, leading to compromised devices.\n\n✅ Solution:\nProviding a simple checklist can help users make safer choices.",
        "3": "Digital Literacy & Security Tips\n\n✔ Enable Google Play Protect to detect malware.\n✔ Use antivirus software on your device.\n✔ Be cautious of apps that offer \"premium unlocked\" features for free.\n\n🚨 The Reality:\n🔸 Many piracy users ignore security risks due to convenience.\n\n✅ Solution:\nBoosting digital literacy programs can reduce APK piracy rates.",
        "4": "Support for Developers & Legal Purchases\n\n✔ Find legitimately discounted apps (e.g., student plans).\n✔ Support developers to encourage better app quality.\n\n🚨 The Reality:\n🔸 Many people don’t realize how easy it is to find legal options.\n\n✅ Solution:\nPromoting affordable legal alternatives can reduce reliance on piracy."
      }
    }
  }