export const iconTexts = {
    "information": {
      "0": {
        "1": "User Motivations \n\n 📌 Finding from the Study: \n Users prioritize cost savings and convenience over ethical considerations, making unauthorized APKs an attractive option. \n\n 🔹 Abhijithoyur (2023) found that cost savings are the primary motivation for engaging in digital piracy. \n\n 📌 What This Means:\n✔ Users prioritize free access over ethics, often rationalizing piracy.\n✔ Many believe piracy doesn't harm developers or businesses.\n✔ Some feel justified in downloading pirated APKs when apps are region-locked or unavailable.\n\n🚨 The Reality:\n🔸 Unauthorized APK downloads expose users to malware, security risks, and legal consequences.\n🔸 Developers lose revenue, affecting their ability to create and update apps.\n\n✅ Solution:\nDevelopers should offer affordable pricing models, free trials, and student discounts to provide legal alternatives.",
        "2": "Cost-Saving as the Main Reason \n\n📌 Finding from the Study:\nThe financial barrier to purchasing apps is the most common reason for APK piracy.\n\n🔹 Maria & Maria (2024) found that users prioritize financial savings over premium features, especially when free apps offer similar functionality\n\n📌 What This Means:\n✔ Many users perceive paid apps as non-essential.\n✔ If a free alternative exists, users see no reason to pay.\n✔ Piracy becomes a habit, reinforcing free access expectations.\n\n🚨 The Reality:\n🔸 Paid apps struggle to compete with \"free\" pirated versions, even when they provide better security and support.\n🔸 Developers may increase app prices due to revenue losses, making piracy even more tempting\n\n✅ Solution:\nImplementing tiered pricing models and regional discounts can encourage users to choose legal options.",
        "3": "Ethics vs. Convenience\n\n📌 Finding from the Study:\nMany users acknowledge that piracy is unethical but still justify it based on convenience.\n\n🔹 Chin et al. (2021) found that users often ignore ethical concerns when piracy is the easiest option.\n\n📌 What This Means:\n✔ Users don’t see piracy as \"stealing,\" especially when it’s easy and anonymous.\n✔ Ethical concerns are often secondary to immediate benefits.\n\n🚨 The Reality:\n🔸 Ethical awareness alone doesn’t stop piracy—users need incentives to change behavior.\n🔸 The longer users engage in piracy, the harder it is for them to transition to legal alternatives.\n\n✅ Solution:\nPromoting legal, convenient alternatives with free trials and flexible payment plans can reduce piracy.",
        "4": "Lack of Awareness of Legal Risks \n\n📌 Finding from the Study:\nMany users do not fully understand the legal consequences of piracy.\n\n🔹 Tomczyk & Fedeli (2021) found that piracy remains widespread despite anti-piracy laws, as many users believe they won’t be caught.\n\n📌 What This Means:\n✔ Users assume piracy is a low-risk activity.\n✔ Laws against piracy are not well-communicated.\n\n🚨 The Reality:\n🔸 Many unauthorized APKs contain malware, leading to data breaches and identity theft.\n🔸 Legal action is increasing, making piracy riskier than before.\n\n✅ Solution:\nDigital literacy campaigns should inform users about piracy risks and legal consequences.",
        "5": "Role of Technology in Piracy\n\n📌 Finding from the Study:\Technology has made piracy easier but also increased cybersecurity threats.\n\n🔹 Li, Liao, & Xie (2021) found that piracy negatively impacts creative productivity and customer support in software industries.\n\n📌 What This Means:\n✔ Faster downloads and file-sharing platforms have fueled piracy growth.\n✔ Users often assume technological workarounds (VPNs, modded apps) will protect them.\n\n🚨 The Reality:\n🔸 Piracy continues to evolve, making enforcement difficult.\n🔸 More advanced malware attacks now specifically target APK piracy users.\n\n✅ Solution:\nEducating users on the risks of piracy-driven malware can encourage safer digital choices.",
        "6": "Faster Internet’s Impact on Piracy\n\n📌 Finding from the Study:\nFaster internet speeds increase unauthorized APK downloads by removing accessibility barriers.\n\n🔹 Citak (2023) found that high-speed internet allows illegal websites to distribute pirated content quickly and anonymously.\n\n📌 What This Means:\n✔ High-speed access removes deterrents, making piracy effortless.\n✔ Users become more dependent on piracy when downloads are instant.\n\n🚨 The Reality:\n🔸 Faster internet enables widespread malware infections through pirated content.\n🔸 Legitimate platforms struggle to compete with the convenience of illegal downloads.\n\n✅ Solution:\nLegal streaming and app platforms must offer affordable, high-quality services to discourage piracy."
      },
      "1": {
        "1": "Qualitative Findings: User Psychology & Perceptions\n\nJustification & Rationalization of Piracy\n\n📌 Finding from the Study:\nUsers don’t always see piracy as wrong, especially when apps are expensive or unavailable in their region.\n\n🔹 Chin et al. (2021) found that users justify piracy as a necessary alternative when official versions are inaccessible.\n\n📌 What This Means:\n✔ Users believe piracy is a workaround for unfair restrictions.\n✔ Some rationalize it by claiming companies already make enough money.\n\n🚨 The Reality:\n🔸 Piracy undermines the business models of developers, forcing them to adopt more restrictive monetization practices.\n\n✅ Solution:\nDevelopers should provide affordable, accessible alternatives such as regional pricing and freemium models.",
        "2": "Qualitative Findings: User Psychology & Perceptions\n\nPerceived Security of Unauthorized Apps\n\n📌 Finding from the Study:\nUsers assume some piracy sources are safe because they have not experienced security issues.\n\n🔹 De Leon et al. (2021) found that many MOD APKs contain hidden malware, exposing users to serious risks.\n\n📌 What This Means:\n✔ Users feel a false sense of security when using \"trusted\" piracy sources.\n\n🚨 The Reality:\n🔸 Even \"safe\" sources can embed spyware that activates later.\n🔸 Users unknowingly compromise personal data and financial accounts\n\n✅ Solution:\nRaising cybersecurity awareness about how hackers exploit APK piracy can help users avoid unsafe downloads.",
        "3": "Qualitative Findings: User Psychology & Perceptions\n\nAnti-Piracy Efforts vs. Workarounds\n\n📌 Finding from the Study:\nDespite anti-piracy laws and security measures, users find workarounds to continue piracy.\n\n🔹 Li, Liao, & Xie (2021) found that piracy constantly evolves alongside security measures.\n\n📌 What This Means:\n✔ Anti-piracy measures are often temporary solutions, as users find ways to bypass them.\n\n🚨 The Reality:\n🔸 Digital piracy is an ever-evolving problem requiring continuous monitoring and stricter enforcement.\n\n✅ Solution:\nStrengthening app security and piracy detection systems can help prevent APK modifications.",
        "4": "Qualitative Findings: User Psychology & Perceptions\n\nRisk Awareness vs. Convenience\n\n📌 Finding from the Study:\nMany users know the risks of piracy but still prioritize convenience.\n\n🔹 Chin et al. (2021) observed that users disregard security warnings when pirated apps offer immediate benefits.\n\n📌 What This Means:\n✔ Users believe short-term benefits outweigh risks.\n✔ Many assume security risks are exaggerated.\n\n🚨 The Reality:\n🔸 Pirated APKs often come with long-term security threats, including identity theft and financial fraud.\n\n✅ Solution:\nEducating users on the hidden dangers of piracy can shift perceptions.",
        "5": "Qualitative Findings: User Psychology & Perceptions\n\nDigital Literacy & Awareness\n\n📌 Finding from the Study:\nMany users lack proper education on piracy risks, leading to unsafe downloading habits.\n\n🔹 Tomczyk & Fedeli (2021) found that digital literacy campaigns significantly reduce piracy rates by informing users of security risks.\n\n📌 What This Means:\n✔ Users are not fully aware of the dangers associated with piracy.\n\n🚨 The Reality:\n🔸 Without proper awareness, users are more vulnerable to cyberattacks.\n\n✅ Solution:\nGovernments and organizations should support educational initiatives that teach users about safe digital practices and legal alternatives.",
        "6": "Quantitative Findings: Behavioral & Economic Impact\n\nFrequent Downloaders vs. Paid App Users\n\n📌 Finding from the Study:\nFrequent APK downloaders continue pirating apps out of habit, even when they can afford legal versions.\n\n🔹 Tomczyk (2021) found that habitual users disregard cost considerations when choosing between free and paid apps.\n\n📌 What This Means:\n✔ Even when apps are affordable, users stick to piracy due to familiarity.\n\n🚨 The Reality:\n🔸 Developers lose revenue, reducing investment in new features and security.\n\n✅ Solution:\nEducating users on the benefits of legal apps (security, reliability, and better user experience) can encourage them to transition away from piracy.",
        "7": "Quantitative Findings: Behavioral & Economic Impact\n\nImpact of Pricing & Accessibility\n\n📌 Finding from the Study:\nHigh app costs push users toward piracy, reinforcing the affordability-piracy link.\n\n🔹 Suarez et al. (2023) found that users perceive expensive apps as non-essential, leading them to seek free alternatives.\n\n📌 What This Means:\n✔ Many users cannot justify paying high prices for an app they use casually.\n\n🚨 The Reality:\n🔸 Overpriced apps lead to more piracy, rather than increased legitimate purchases.\n\n✅ Solution:\nImplementing flexible pricing models (freemium plans, student discounts, or regional pricing) can make legal purchases more accessible.",
        "8": "Quantitative Findings: Behavioral & Economic Impact\n\nCorrelation Between Technology & APK Downloads\n\n📌 Finding from the Study:\nTechnological advancements increase APK piracy rates by making piracy faster and more accessible.\n\n🔹 Li, Liao, & Xie (2021) found that digital piracy evolves alongside security measures, making enforcement difficult.\n\n📌 What This Means:\n✔ As new tools make piracy easier, illegal downloads increase.\n\n🚨 The Reality:\n🔸 Traditional anti-piracy measures become outdated fast, requiring constant adaptation.\n\n✅ Solution:\nStronger AI-driven piracy detection systems and collaborations between developers and cybersecurity firms can help reduce piracy.",
        "9": "Quantitative Findings: Behavioral & Economic Impact\n\nFree Alternatives & Piracy Behavior\n\n📌 Finding from the Study:\nThe availability of free alternatives increases piracy rates.\n\n🔹 Tian et al. (2021) found that users prefer free apps over paid ones, even if the experience is lower quality.\n\n📌 What This Means:\n✔ Free versions encourage habitual piracy, as users always choose the cheaper option.\n\n🚨 The Reality:\n🔸 The more free apps exist, the more piracy is normalized.\n\n✅ Solution:\nOffering better incentives for legal purchases (exclusive features, bonuses, or cross-app benefits) can encourage users to buy official apps."
      },
      "3": {
        "1": "i31",
        "2": "i32",
        "3": "i33",
        "4": "i34",
        "5": "i35",
        "6": "i36",
        "7": "i37",
        "8": "i38",
        "9": "i39",
        "10": "1310"
      }
    },
    "guide": {
      "0": {
        "1": "g01",
        "2": "g02",
        "3": "g03",
        "4": "g04",
        "5": "g05"
      },
      "1": {
        "1": "g11",
        "2": "g12",
        "3": "g13",
        "4": "g14"
      },
      "3": {
        "1": "g31",
        "2": "g32"
      },
      "4": {
        "1": "g41",
        "2": "g42",
        "3": "g43",
        "4": "g44"
      }
    }
  }